### ISSUE TITLE
`Promise<P>` in `GetServerSidePropsResult`

### ISSUE THREAD

**Issue by freeatnet** [HaNdTriX/infer-next-props-type#1]
Hey @HaNdTriX! Thank you for patching inferred types in https://github.com/vercel/next.js/pull/40635.

I noticed that `InferGetServerSidePropsType` type is wrapped in an `Awaited` in the [contributed patch;](https://github.com/HaNdTriX/next.js/blob/d4e658835471020d341f98ea5ba91e7adfe91849/packages/next/types/index.d.ts#L181) however, it's missing from this package.

Is there any chance you could backport it into this package? I know you tagged it as "deprecated," but I would very much appreciate this fix as the next version of Next seems to contain quite a few breaking changes.

**Comment by HaNdTriX** [comment]
Good catch! Thanks for reporting this!

**Comment by HaNdTriX** [comment]
https://github.com/HaNdTriX/infer-next-props-type/releases/tag/v0.1.0
